DROP TABLE detalle_pedido CASCADE CONSTRAINTS;
DROP TABLE pagos CASCADE CONSTRAINTS;
DROP TABLE sucursal CASCADE CONSTRAINTS;
DROP TABLE categoria CASCADE CONSTRAINTS;
DROP TABLE producto CASCADE CONSTRAINTS;
DROP TABLE detalle_carrito CASCADE CONSTRAINTS;
DROP TABLE pedido CASCADE CONSTRAINTS;
DROP TABLE carrito_compra CASCADE CONSTRAINTS;
DROP TABLE cliente CASCADE CONSTRAINTS;
DROP TABLE credencial CASCADE CONSTRAINTS;
DROP TABLE usuario CASCADE CONSTRAINTS;
DROP TABLE genero CASCADE CONSTRAINTS;
DROP TABLE rol CASCADE CONSTRAINTS;


CREATE TABLE rol (
    id_rol NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_rol VARCHAR2(50) UNIQUE NOT NULL,
    CONSTRAINT rol_pk PRIMARY KEY (id_rol)
);

CREATE TABLE genero (
    id_genero NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(50) UNIQUE NOT NULL,
    CONSTRAINT genero_pk PRIMARY KEY (id_genero)
);

CREATE TABLE usuario (
    id_usuario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    rut VARCHAR2(20) UNIQUE NOT NULL,
    direccion VARCHAR2(255),
    telefono VARCHAR2(20),
    email VARCHAR2(100) UNIQUE NOT NULL,
    fecha_nacimiento DATE,
    id_rol NUMBER NOT NULL,
    id_genero NUMBER,
    CONSTRAINT usuario_pk PRIMARY KEY (id_usuario),
    CONSTRAINT usuario_fk_rol FOREIGN KEY (id_rol) REFERENCES rol(id_rol),
    CONSTRAINT usuario_fk_genero FOREIGN KEY (id_genero) REFERENCES genero(id_genero)
);

CREATE TABLE credencial (
    id_credencial NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario NUMBER UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    contrasena VARCHAR2(255) NOT NULL,
    CONSTRAINT credencial_pk PRIMARY KEY (id_credencial),
    CONSTRAINT credencial_fk_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE cliente (
    id_cliente NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario NUMBER UNIQUE NOT NULL,
    informacion_adicional_cliente VARCHAR2(255),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT clientes_pk PRIMARY KEY (id_cliente),
    CONSTRAINT clientes_fk_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE carrito_compra (
    id_carrito NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_cliente NUMBER NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR2(50) DEFAULT 'Activo',
    CONSTRAINT carrito_pk PRIMARY KEY (id_carrito),
    CONSTRAINT carrito_fk_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente)
);

CREATE TABLE pedido (
    id_pedido NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_cliente NUMBER NOT NULL,
    fecha_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR2(50) DEFAULT 'Pendiente',
    id_usuario_vendedor NUMBER,
    id_usuario_contador NUMBER,
    id_usuario_bodeguero NUMBER,
    fecha_entrega DATE,
    direccion_envio VARCHAR2(255) NOT NULL,
    total NUMBER(10, 2) NOT NULL,
    CONSTRAINT pedido_pk PRIMARY KEY (id_pedido),
    CONSTRAINT pedido_fk_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    CONSTRAINT pedido_fk_vendedor FOREIGN KEY (id_usuario_vendedor) REFERENCES usuario(id_usuario),
    CONSTRAINT pedido_fk_contador FOREIGN KEY (id_usuario_contador) REFERENCES usuario(id_usuario),
    CONSTRAINT pedido_fk_bodeguero FOREIGN KEY (id_usuario_bodeguero) REFERENCES usuario(id_usuario)
);

CREATE TABLE categoria (
    id_categoria NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(200) NOT NULL,
    descripcion VARCHAR2(500),
    CONSTRAINT categoria_pk PRIMARY KEY (id_categoria)
);

CREATE TABLE producto (
    id_producto NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(200) NOT NULL,
    descripcion CLOB,
    precio NUMBER(10, 2) NOT NULL,
    stock NUMBER DEFAULT 0 NOT NULL,
    imagen VARCHAR2(255),
    marca VARCHAR2(100),
    modelo VARCHAR2(255),
    codigo VARCHAR2(50) UNIQUE,
    id_categoria NUMBER NOT NULL,
    CONSTRAINT producto_pk PRIMARY KEY (id_producto),
    CONSTRAINT producto_fk_categoria FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria)
);

CREATE TABLE detalle_carrito (
    id_detalle_carrito NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_carrito NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    cantidad NUMBER NOT NULL CONSTRAINT chk_cantidad_carrito CHECK (cantidad > 0),
    precio_unitario NUMBER(10, 2) NOT NULL,
    CONSTRAINT detalle_carrito_pk PRIMARY KEY (id_detalle_carrito),
    CONSTRAINT detalle_carrito_fk_carrito FOREIGN KEY (id_carrito) REFERENCES carrito_compra(id_carrito),
    CONSTRAINT detalle_carrito_fk_producto FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
);

CREATE TABLE sucursal (
    id_sucursal NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(255) NOT NULL,
    direccion VARCHAR2(255) NOT NULL,
    celular VARCHAR2(20),
    telefono VARCHAR2(20),
    CONSTRAINT sucursal_pk PRIMARY KEY (id_sucursal)
);

CREATE TABLE pago (
    id_pago NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_pedido NUMBER NOT NULL,
    metodo VARCHAR2(100) NOT NULL,
    fecha_pago DATE NOT NULL,
    monto NUMBER(10, 2) NOT NULL,
    estado VARCHAR2(50) NOT NULL,
    CONSTRAINT pago_pk PRIMARY KEY (id_pago),
    CONSTRAINT pago_fk_pedido FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido)
);

CREATE TABLE detalle_pedido (
    id_detalle_pedido NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_pedido NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    cantidad NUMBER NOT NULL CONSTRAINT chk_cantidad_pedido CHECK (cantidad > 0),
    precio NUMBER(10, 2) NOT NULL,
    subtotal NUMBER(10, 2) NOT NULL,
    CONSTRAINT detalle_pedido_pk PRIMARY KEY (id_detalle_pedido),
    CONSTRAINT detalle_pedido_fk_pedido FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
    CONSTRAINT detalle_pedido_fk_producto FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
);

-- Insertar datos de ejemplo

--Genero
INSERT INTO genero (id_genero, nombre) VALUES (1, 'Masculino');
INSERT INTO genero (id_genero, nombre) VALUES (2, 'Femenino');
INSERT INTO genero (id_genero, nombre) VALUES (3, 'Otro');
INSERT INTO genero (id_genero, nombre) VALUES (4, 'No especificado');

--Rol
INSERT INTO rol (id_rol, nombre_rol) VALUES (1, 'Administrador');
INSERT INTO rol (id_rol, nombre_rol) VALUES (2, 'Vendedor');
INSERT INTO rol (id_rol, nombre_rol) VALUES (3, 'Contador');
INSERT INTO rol (id_rol, nombre_rol) VALUES (4, 'Bodeguero');
INSERT INTO rol (id_rol, nombre_rol) VALUES (5, 'Cliente');

--Usuario
-- Admin
INSERT INTO usuario (nombre, apellido, rut, direccion, telefono, fecha_nacimiento, email, id_rol)
VALUES ('Admin', 'General', '00000000-0', 'Central 123', '000000000', TO_DATE('1980-01-01', 'YYYY-MM-DD'), 'admin@ferremas.cl', 1);

-- Vendedores
INSERT INTO usuario (nombre, apellido, rut, direccion, telefono, fecha_nacimiento, email, id_rol)
VALUES ('Carlos', 'Vega', '11111111-1', 'Calle 1', '111111111', TO_DATE('1990-05-20', 'YYYY-MM-DD'), 'carlos.vega@ferremas.cl', 2);

INSERT INTO usuario (nombre, apellido, rut, direccion, telefono, fecha_nacimiento, email, id_rol)
VALUES ('Lucía', 'Pérez', '22222222-2', 'Calle 2', '222222222', TO_DATE('1992-07-15', 'YYYY-MM-DD'), 'lucia.perez@ferremas.cl', 2);

-- Bodegueros
INSERT INTO usuario (nombre, apellido, rut, direccion, telefono, fecha_nacimiento, email, id_rol)
VALUES ('Marco', 'Díaz', '33333333-3', 'Calle 3', '333333333', TO_DATE('1985-09-10', 'YYYY-MM-DD'), 'marco.diaz@ferremas.cl', 3);

INSERT INTO usuario (nombre, apellido, rut, direccion, telefono, fecha_nacimiento, email, id_rol)
VALUES ('Sandra', 'Torres', '44444444-4', 'Calle 4', '444444444', TO_DATE('1988-12-12', 'YYYY-MM-DD'), 'sandra.torres@ferremas.cl', 3);

-- Contadores
INSERT INTO usuario (nombre, apellido, rut, direccion, telefono, fecha_nacimiento, email, id_rol)
VALUES ('Antonio', 'Ramírez', '55555555-5', 'Calle 5', '555555555', TO_DATE('1983-03-30', 'YYYY-MM-DD'), 'antonio.ramirez@ferremas.cl', 4);

INSERT INTO usuario (nombre, apellido, rut, direccion, telefono, fecha_nacimiento, email, id_rol)
VALUES ('Patricia', 'González', '66666666-6', 'Calle 6', '666666666', TO_DATE('1986-11-25', 'YYYY-MM-DD'), 'patricia.gonzalez@ferremas.cl', 4);

-- Clientes
INSERT INTO usuario (nombre, apellido, rut, direccion, telefono, fecha_nacimiento, email, id_rol)
VALUES ('Juan', 'López', '77777777-7', 'Av. Cliente 1', '777777777', TO_DATE('1995-04-18', 'YYYY-MM-DD'), 'juan.lopez@ferremas.cl', 5);

INSERT INTO usuario (nombre, apellido, rut, direccion, telefono, fecha_nacimiento, email, id_rol)
VALUES ('Marta', 'Hernández', '88888888-8', 'Av. Cliente 2', '888888888', TO_DATE('1998-06-05', 'YYYY-MM-DD'), 'marta.hernandez@ferremas.cl', 5);

-- Categoría
INSERT INTO categoria (nombre, descripcion) VALUES ('Herramientas manuales', 'Herramientas que funcionan sin electricidad.');
INSERT INTO categoria (nombre, descripcion) VALUES ('Herramientas eléctricas', 'Herramientas que requieren electricidad para funcionar.');
INSERT INTO categoria (nombre, descripcion) VALUES ('Materiales de construcción', 'Materiales utilizados en la edificación.');
INSERT INTO categoria (nombre, descripcion) VALUES ('Pinturas y acabados', 'Productos para pintar y dar acabado.');
INSERT INTO categoria (nombre, descripcion) VALUES ('Fontanería', 'Productos para instalaciones hidráulicas.');

-- Productos
-- Herramientas manuales
INSERT INTO producto (nombre, descripcion, precio, stock, imagen, marca, modelo, codigo, id_categoria)
VALUES ('Martillo de carpintero', 'Martillo con mango de madera y cabeza de acero.', 8.50, 100, 'https://m.media-amazon.com/images/I/51t+6dFdcQL._AC_SY300_SX300_.jpg', 'Stanley', 'STHT51304', 'HM001', 1);

INSERT INTO producto (nombre, descripcion, precio, stock, imagen, marca, modelo, codigo, id_categoria)
VALUES ('Destornillador plano', 'Destornillador con punta plana y mango ergonómico.', 3.25, 150, 'https://www.truper.com/media/import/imagenes/DR-3-16X4B.jpg', 'Truper', 'DES-3', 'HM002', 1);

-- Herramientas eléctricas
INSERT INTO producto (nombre, descripcion, precio, stock, imagen, marca, modelo, codigo, id_categoria)
VALUES ('Taladro eléctrico', 'Taladro de 500W con velocidad variable.', 45.00, 60, 'https://m.media-amazon.com/images/I/513AKYMbGdL._AC_SX425_.jpg', 'Bosch', 'GSB 550', 'HE001', 2);

INSERT INTO producto (nombre, descripcion, precio, stock, imagen, marca, modelo, codigo, id_categoria)
VALUES ('Amoladora angular', 'Amoladora de 115mm, ideal para corte y pulido.', 60.00, 40, 'https://www.hilti.cl/medias/sys_master/images/h29/h0d/10043307196446.jpg', 'Makita', '9557HNG', 'HE002', 2);

-- Materiales de construcción
INSERT INTO producto (nombre, descripcion, precio, stock, imagen, marca, modelo, codigo, id_categoria)
VALUES ('Cemento Portland', 'Bolsa de cemento de 42.5 kg.', 7.00, 200, 'https://media.adeo.com/media/1827587/media.png?width=3000&height=3000&format=jpg&quality=80&fit=bounds', 'Holcim', 'CEM42', 'MC001', 3);

INSERT INTO producto (nombre, descripcion, precio, stock, imagen, marca, modelo, codigo, id_categoria)
VALUES ('Ladrillo rojo', 'Ladrillo macizo de arcilla.', 0.25, 1000, 'https://http2.mlstatic.com/D_NQ_NP_636243-CBT80913088029_112024-O.webp', 'Ladrillera Nacional', 'LR100', 'MC002', 3);

-- Pinturas y acabados
INSERT INTO producto (nombre, descripcion, precio, stock, imagen, marca, modelo, codigo, id_categoria)
VALUES ('Pintura blanca interior', 'Pintura látex blanca para interiores, 4L.', 15.00, 80, 'https://media.falabella.com/sodimacCL/7409540_01/w=1500,h=1500,fit=pad', 'Sherwin Williams', 'Interior Blanco', 'PA001', 4);

INSERT INTO producto (nombre, descripcion, precio, stock, imagen, marca, modelo, codigo, id_categoria)
VALUES ('Rodillo de pintura', 'Rodillo de microfibra para acabados finos.', 4.50, 120, 'https://media.falabella.com/sodimacCL/3494543_01/w=1500,h=1500,fit=pad', 'Truper', 'ROD-9MF', 'PA002', 4);

-- Fontanería
INSERT INTO producto (nombre, descripcion, precio, stock, imagen, marca, modelo, codigo, id_categoria)
VALUES ('Tubería PVC 1"', 'Tubo de PVC para agua fría, 3 metros.', 2.75, 300, 'https://corporacionmercantil.cdn1.dattamax.com/userfiles/images/productos/600/4375-tubo-cloacal-blanco-100.jpg', 'Tigre', 'PVC100', 'FO001', 5);

INSERT INTO producto (nombre, descripcion, precio, stock, imagen, marca, modelo, codigo, id_categoria)
VALUES ('Llave de paso', 'Llave de paso metálica de 1/2 pulgada.', 5.80, 200, 'https://www.sharkbite.com/sites/default/files/styles/500x375/public/images/23036-0000LF-product-photo.png.jpeg?itok=bzkGmYKv', 'Ferroval', 'LVP12', 'FO002', 5);
