DROP TABLE detalle_pedido CASCADE CONSTRAINTS;
DROP TABLE pagos CASCADE CONSTRAINTS;
DROP TABLE sucursal CASCADE CONSTRAINTS;
DROP TABLE categoria CASCADE CONSTRAINTS;
DROP TABLE producto CASCADE CONSTRAINTS;
DROP TABLE detalle_carrito CASCADE CONSTRAINTS;
DROP TABLE pedido CASCADE CONSTRAINTS;
DROP TABLE carrito_compra CASCADE CONSTRAINTS;
DROP TABLE cliente CASCADE CONSTRAINTS;
DROP TABLE credencial CASCADE CONSTRAINTS;
DROP TABLE usuario CASCADE CONSTRAINTS;
DROP TABLE genero CASCADE CONSTRAINTS;
DROP TABLE rol CASCADE CONSTRAINTS;


CREATE TABLE rol (
    id_rol NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_rol VARCHAR2(50) UNIQUE NOT NULL,
    CONSTRAINT rol_pk PRIMARY KEY (id_rol)
);

CREATE TABLE genero (
    id_genero NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(50) UNIQUE NOT NULL,
    CONSTRAINT genero_pk PRIMARY KEY (id_genero)
);

CREATE TABLE usuario (
    id_usuario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    rut VARCHAR2(20) UNIQUE NOT NULL,
    direccion VARCHAR2(255),
    telefono VARCHAR2(20),
    fecha_nacimiento DATE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_rol NUMBER NOT NULL,
    id_genero NUMBER,
    CONSTRAINT usuario_pk PRIMARY KEY (id_usuario),
    CONSTRAINT usuario_fk_rol FOREIGN KEY (id_rol) REFERENCES rol(id_rol),
    CONSTRAINT usuario_fk_genero FOREIGN KEY (id_genero) REFERENCES genero(id_genero)
);

CREATE TABLE credencial (
    id_credencial NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario NUMBER UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    contrasena VARCHAR2(255) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ultimo_login TIMESTAMP,
    CONSTRAINT credencial_pk PRIMARY KEY (id_credencial),
    CONSTRAINT credencial_fk_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE cliente (
    id_cliente NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario NUMBER UNIQUE NOT NULL,
    informacion_adicional_cliente VARCHAR2(255),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT clientes_pk PRIMARY KEY (id_cliente),
    CONSTRAINT clientes_fk_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);

CREATE TABLE carrito_compra (
    id_carrito NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_cliente NUMBER NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT carrito_pk PRIMARY KEY (id_carrito),
    CONSTRAINT carrito_fk_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente)
);

CREATE TABLE pedido (
    id_pedido NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_cliente NUMBER NOT NULL,
    fecha_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR2(50) DEFAULT 'Pendiente',
    id_usuario_vendedor NUMBER,
    id_usuario_contador NUMBER,
    id_usuario_bodeguero NUMBER,
    fecha_entrega DATE,
    direccion_envio VARCHAR2(255) NOT NULL,
    total NUMBER(10, 2) NOT NULL,
    CONSTRAINT pedido_pk PRIMARY KEY (id_pedido),
    CONSTRAINT pedido_fk_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    CONSTRAINT pedido_fk_vendedor FOREIGN KEY (id_usuario_vendedor) REFERENCES usuario(id_usuario),
    CONSTRAINT pedido_fk_contador FOREIGN KEY (id_usuario_contador) REFERENCES usuario(id_usuario),
    CONSTRAINT pedido_fk_bodeguero FOREIGN KEY (id_usuario_bodeguero) REFERENCES usuario(id_usuario)
);

CREATE TABLE detalle_carrito (
    id_detalle_carrito NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_carrito NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    cantidad NUMBER NOT NULL CONSTRAINT chk_cantidad_carrito CHECK (cantidad > 0),
    precio_unitario NUMBER(10, 2) NOT NULL,
    CONSTRAINT detalle_carrito_pk PRIMARY KEY (id_detalle_carrito),
    CONSTRAINT detalle_carrito_fk_carrito FOREIGN KEY (id_carrito) REFERENCES carrito_de_compra(id_carrito),
    CONSTRAINT detalle_carrito_fk_producto FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
);

CREATE TABLE producto (
    id_producto NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(200) NOT NULL,
    descripcion CLOB,
    precio NUMBER(10, 2) NOT NULL,
    stock NUMBER DEFAULT 0 NOT NULL,
    imagen VARCHAR2(255),
    marca VARCHAR2(100),
    modelo VARCHAR2(255),
    codigo VARCHAR2(50) UNIQUE,
    id_categoria NUMBER NOT NULL,
    CONSTRAINT producto_pk PRIMARY KEY (id_producto),
    CONSTRAINT producto_fk_categoria FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria)
);

CREATE TABLE categoria (
    id_categoria NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(200) NOT NULL,
    descripcion VARCHAR2(500),
    CONSTRAINT categoria_pk PRIMARY KEY (id_categoria)
);

CREATE TABLE sucursal (
    id_sucursal NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(255) NOT NULL,
    direccion VARCHAR2(255) NOT NULL,
    celular VARCHAR2(20),
    telefono VARCHAR2(20),
    CONSTRAINT sucursal_pk PRIMARY KEY (id_sucursal)
);

CREATE TABLE pago (
    id_pago NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_pedido NUMBER NOT NULL,
    metodo VARCHAR2(100) NOT NULL,
    fecha_pago DATE NOT NULL,
    monto NUMBER(10, 2) NOT NULL,
    estado VARCHAR2(50) NOT NULL,
    CONSTRAINT pago_pk PRIMARY KEY (id_pago),
    CONSTRAINT pago_fk_pedido FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido)
);

CREATE TABLE detalle_pedido (
    id_detalle_pedido NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_pedido NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    cantidad NUMBER NOT NULL CONSTRAINT chk_cantidad_pedido CHECK (cantidad > 0),
    precio NUMBER(10, 2) NOT NULL,
    subtotal NUMBER(10, 2) NOT NULL,
    CONSTRAINT detalle_pedido_pk PRIMARY KEY (id_detalle_pedido),
    CONSTRAINT detalle_pedido_fk_pedido FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
    CONSTRAINT detalle_pedido_fk_producto FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
);
