version: '3.8'

services:
  fastapi:
    build: ./API/FastApi
    # command: sh -c "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./API/FastApi:/app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - SECRET_KEY=${FASTAPI_SECRET_KEY}
    depends_on:
      - db

  nodejs:
    build: ./API/Nodejs
    ports:
      - "3000:3000"
    volumes:
      - ./API/Nodejs:/app
      - nodejs_node_modules:/app/node_modules
    command: npm run start
    environment:
      - PORT=3000
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - API_KEY=${NODEJS_API_KEY}
    depends_on:
      - db

  db:
    image: container-registry.oracle.com/database/express:latest
    ports:
      - "1522:1521"
    environment:
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
    volumes:
      - db_data:/opt/oracle/oradata

volumes:
  nodejs_node_modules:
  db_data: